package vo;

import java.util.HashSet;
import java.util.Set;



/**
 * Department generated by MyEclipse - Hibernate Tools
 */

public class Department  implements java.io.Serializable {


    // Fields    

     private Integer oid;
     private Integer parentid;
     private String deptName;
     private String phone;
     private String email;
     private String fax;
     private Integer manager;
     private String address;
     private String zipcode;
     private String description;
     private Set employees = new HashSet();


    // Constructors

    /** default constructor */
    public Department() {
    }

    
    /** full constructor */
    public Department(Integer parentid, String deptName, String phone, String email, String fax, Integer manager, String address, String zipcode, String description) {
        this.parentid = parentid;
        this.deptName = deptName;
        this.phone = phone;
        this.email = email;
        this.fax = fax;
        this.manager = manager;
        this.address = address;
        this.zipcode = zipcode;
        this.description = description;
    }

   
    // Property accessors

    public Integer getOid() {
        return this.oid;
    }
    
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    public Integer getParentid() {
        return this.parentid;
    }
    
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    public String getDeptName() {
        return this.deptName;
    }
    
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    public Integer getManager() {
        return this.manager;
    }
    
    public void setManager(Integer manager) {
        this.manager = manager;
    }

    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    public String getZipcode() {
        return this.zipcode;
    }
    
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }


	public Set getEmployees() {
		return employees;
	}


	public void setEmployees(Set employees) {
		this.employees = employees;
	}
   








}